import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { FormField } from '@/lib/pdf/generator'

/* ------------------------------------------------------------------ */
/* Styles                                                              */
/* ------------------------------------------------------------------ */

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottom: '2px solid #1e40af',
  },
  title: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: '#1e40af',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 8,
    color: '#6b7280',
  },
  formType: {
    fontSize: 8,
    color: '#9ca3af',
    marginTop: 2,
  },
  sectionHeading: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: '#1e3a5f',
    backgroundColor: '#eff6ff',
    padding: '6 8',
    marginTop: 14,
    marginBottom: 8,
    borderLeft: '3px solid #1e40af',
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingVertical: 3,
    paddingHorizontal: 4,
    borderBottom: '0.5px solid #e5e7eb',
  },
  fieldLabel: {
    width: '40%',
    fontSize: 9,
    color: '#4b5563',
    fontFamily: 'Helvetica',
  },
  fieldValue: {
    width: '60%',
    fontSize: 9,
    color: '#111827',
    fontFamily: 'Helvetica-Bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: '1px solid #d1d5db',
    paddingTop: 8,
  },
  footerText: {
    fontSize: 7,
    color: '#9ca3af',
  },
  disclaimer: {
    marginTop: 20,
    padding: 8,
    backgroundColor: '#fefce8',
    border: '1px solid #fde68a',
    fontSize: 7,
    color: '#92400e',
    lineHeight: 1.4,
  },
})

/* ------------------------------------------------------------------ */
/* Component                                                           */
/* ------------------------------------------------------------------ */

interface FormPdfDocumentProps {
  title: string
  fields: FormField[]
  formType: string
}

export function FormPdfDocument({ title, fields, formType }: FormPdfDocumentProps) {
  // Group fields by section
  const sections: { heading: string; fields: FormField[] }[] = []
  let currentSection: { heading: string; fields: FormField[] } = { heading: 'General Information', fields: [] }

  for (const field of fields) {
    if (field.section && field.section !== currentSection.heading) {
      if (currentSection.fields.length > 0) {
        sections.push(currentSection)
      }
      currentSection = { heading: field.section, fields: [] }
    }
    currentSection.fields.push(field)
  }
  if (currentSection.fields.length > 0) {
    sections.push(currentSection)
  }

  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>Generated by BlastTax — DIY Tax Resolution Platform</Text>
          <Text style={styles.formType}>Form Type: {formType} | Generated: {generatedDate}</Text>
        </View>

        {/* Sections */}
        {sections.map((section, sIdx) => (
          <View key={sIdx} wrap={false}>
            <Text style={styles.sectionHeading}>{section.heading}</Text>
            {section.fields.map((field, fIdx) => (
              <View key={fIdx} style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>{field.label}</Text>
                <Text style={styles.fieldValue}>{field.value || '—'}</Text>
              </View>
            ))}
          </View>
        ))}

        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text>
            IMPORTANT: This document was generated for informational and preparation purposes by BlastTax.
            It is NOT a substitute for the official IRS form. You must transfer these values to the official
            IRS form before submission. Verify all information is accurate before filing. Consult a qualified
            tax professional if you have questions about your specific situation.
          </Text>
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>BlastTax — {title}</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}
